# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: subscriptionId
    value: 'd4e56fca-114c-4a87-b670-1f039b63445c'
  - name: resourceGroup
    value: 'PAM.Common'
  - name: containerRegistryName
    value: crpamprod
  - name: containerConnection
    value: '{"loginServer":"$(containerRegistryName).azurecr.io", "id" : "/subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroup)/providers/Microsoft.ContainerRegistry/registries/$(containerRegistryName)"}'

steps:
  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'ikea'
  
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
  
  - task: CopyFiles@2
    displayName: 'Copy files to staging folder'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**/*.jar'
      TargetFolder: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: icomdev.pam-asset-type-service'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
  
  # Build container image PROD
  - task: Docker@0
    displayName: 'Build an image for production'
    inputs:
      azureSubscription: 'sc-oneui-ikeaorderandcreate-prd'
      dockerFile: '**/Dockerfile'
      imageName: $(Build.Repository.Name):$(Build.BuildId)
      action: 'Build an image'
      azureContainerRegistry: $(containerConnection)
      includeLatestTag: true
  
  # Push container image PROD
  - task: Docker@0
    displayName: 'Push an image to production'
    inputs:
      azureSubscription: 'sc-oneui-ikeaorderandcreate-prd'
      imageName: $(Build.Repository.Name):$(Build.BuildId)
      azureContainerRegistry: $(containerConnection)
      action: 'Push an image'
      includeLatestTag: true
